### PR TITLE
refactoring of font size

### PR DESCRIPTION
**Pull request by nozaki-kun**
font size is refactor for various device in side the html

### CODE REVIEW

**Review by wakemaru — COMMENTED** [review]
the font size percentage should be 62.5 and it should be applied in body

**Comment by nozaki-kun** [comment]
> the font size percentage should be 62.5 and it should be applied in body

ok i will change

**Comment by nozaki-kun** [comment]
> the font size percentage should be 62.5 and it should be applied in body

i haved changed it pls check it

**Review by wakemaru — APPROVED** [review]
grt

**Pull request merged**
